version: '3'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "1200:1200"
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
    ports:
      - "1900:1900"
    depends_on:
      - backend

  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: pdv
      POSTGRES_USER: pdv
      POSTGRES_PASSWORD: pdv@9185
    ports:
      - "5432:5432"